### ISSUE TITLE
R3 master lauch.sh throws errors

### ISSUE THREAD

**Issue by Kingbadger3d** [intel-iot-devkit/intelligent-classroom#4]
Hi guys,

Good to see the example has been updated but when i try to run ./lauch.sh I get the following errors:

Installing Classroom Analytics Container, Please Wait..
l_openvino_toolkit_p_2019.3.334.tgz not found.
-----------------------------------
 Downloading the OpenVINO tool kit 
-----------------------------------
Downloading OpenVINO. Please wait.
--2019-11-11 17:20:05--  http://registrationcenter-download.intel.com/akdlm/irc_nas/15693/l_openvino_toolkit_p_2019.3.334.tgz
Resolving registrationcenter-download.intel.com (registrationcenter-download.intel.com)... 104.110.244.5, 2a02:26f0:ec:4a2::b, 2a02:26f0:ec:486::b
Connecting to registrationcenter-download.intel.com (registrationcenter-download.intel.com)|104.110.244.5|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /en/irc_nas/15693/l_openvino_toolkit_p_2019.3.334.tgz/ [following]
--2019-11-11 17:20:05--  http://registrationcenter-download.intel.com/en/irc_nas/15693/l_openvino_toolkit_p_2019.3.334.tgz/
Reusing existing connection to registrationcenter-download.intel.com:80.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www-ssl.intel.com/content/www/us/en/404.html?aspxerrorpath=/en/irc_nas/15693/l_openvino_toolkit_p_2019.3.334.tgz/ [following]
--2019-11-11 17:20:06--  https://www-ssl.intel.com/content/www/us/en/404.html?aspxerrorpath=/en/irc_nas/15693/l_openvino_toolkit_p_2019.3.334.tgz/
Resolving www-ssl.intel.com (www-ssl.intel.com)... 104.110.244.5
Connecting to www-ssl.intel.com (www-ssl.intel.com)|104.110.244.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-11 17:20:06 ERROR 404: Not Found.

Do you think it might be because ive just installed the latest openvino r3.1 (l_openvino_toolkit_p_2019.3.376.tgz)

If so should i just edit the script to look for the newer Openvino?

**Comment by zahidulhaque** [comment]
@Kingbadger3d , The link was broken. It is fixed.
Please check now.
